# require: rubocop-rspec

inherit_from:
  - http://relaxed.ruby.style/rubocop.yml

AllCops:
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'config/environments/*.rb'
    - 'bin/*'

# Style/DateTime:
#   Enabled: true

Layout:
  Max: 120

Lint/RedundantCopDisableDirective:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'test/**/*.rb'
    - 'Guardfile'
    - 'vendor/bundle'
    - 'app/admin/productors.rb'
