require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-capybara
  - rubocop-performance

inherit_gem:
  pundit: config/rubocop-rspec.yml

AllCops:
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'bin/*'
  NewCops: enable

Layout/LineLength:
  Max: 120
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Lint/RedundantCopDisableDirective:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'test/**/*.rb'
    - 'Guardfile'
    - 'vendor/bundle'
    # - "app/admin/**/*"
    - 'config/environments/*.rb'
    # - "app/views/admin/**/*"

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'
    - 'spec/**/*'

Style/Documentation:
  Exclude:
    - 'app/controllers/**/*'
  Include:
    - 'app/controllers/concerns/**/*'
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/StringLiterals:
  Exclude:
    - db/schema.rb

# ----------- Extensions overrides -----------
Rails/UnknownEnv:
  Environments:
    - development
    - production
    - staging
    - test

RSpec/NestedGroups:
  AllowedGroups: [describe]
  Max: 3

RSpec/ExampleLength:
  Exclude:
    - 'spec/system/**/*'

# Personal taste
Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required
