---
include:
  - '**/*.rb'
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - '.bundle/**/*'
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
  - typecheck:typed
  # - reek
require_paths: []
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
plugins:
  - solargraph-rails
  - solargraph-reek
max_files: 5000
